owner: petebachant
name: clima-horizontal-diffusion
title: CliMA horizontal diffusion
description: Optimizing performance of horizontal diffusion in ClimaAtmos.
git_repo_url: https://github.com/petebachant/clima-horizontal-diffusion
questions:
  - Why does horizontal diffusion slow down ClimaAtmos so much, and is there
    anything we can do about it?

  - What is the computational cost of constant horizontal diffusion?
environments:
  clima:
    kind: slurm
    host: clima.gps.caltech.edu
  py:
    path: requirements.txt
    kind: uv-venv
    prefix: .venv
    python: "3.13"

pipeline:
  stages:
    nsys-baseline-smag:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/baseline-smag
        - ClimaAtmos.jl/.buildkite
        - config/base.yml
        - config/smag.yml
      inputs:
        - config/base.yml
        - config/smag.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/perf/benchmark_step.jl
      outputs:
        - results/nsys/baseline-smag.nsys-rep
    nsys-baseline-smag-to-sqlite:
      kind: shell-command
      environment: _system
      command: nsys export results/nsys/baseline-smag.nsys-rep -t sqlite
        -o results/nsys/baseline-smag.sqlite
      inputs:
        - results/nsys/baseline-smag.nsys-rep
      outputs:
        - results/nsys/baseline-smag.sqlite
    # Nsight Compute for baseline Smagorinsky
    ncu-baseline-smag:
      kind: sbatch
      environment: clima
      script_path: scripts/run-ncu.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - results/ncu/baseline-smag
        - --kernel-name
        - set_smagorinsky_lilly_precomputed_quantities__FILE_ClimaAtmos_jl_src_parameterized_tendencies_les_sgs_models_smagorinsky_lilly_jl_L66
        - --project
        - ClimaAtmos.jl/.buildkite
        - --config_file
        - config/base.yml
        - --config_file
        - config/smag.yml
        - --launch-count
        - "6"
      inputs:
        - config/base.yml
        - config/smag.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/perf/benchmark_step.jl
      outputs:
        - results/ncu/baseline-smag.ncu-rep
    nsys-mod-smag:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/mod-smag
        - ClimaAtmos.jl-mod/.buildkite
        - config/base.yml
        - config/smag.yml
      inputs:
        - config/base.yml
        - config/smag.yml
        - ClimaAtmos.jl-mod/src
        - ClimaAtmos.jl-mod/toml
        - ClimaAtmos.jl-mod/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/perf/benchmark_step.jl
      outputs:
        - results/nsys/mod-smag.nsys-rep
    nsys-mod-smag-to-sqlite:
      kind: shell-command
      environment: _system
      command: nsys export results/nsys/mod-smag.nsys-rep -t sqlite
        -o results/nsys/mod-smag.sqlite
      inputs:
        - results/nsys/mod-smag.nsys-rep
      outputs:
        - results/nsys/mod-smag.sqlite
    nsys-baseline-const:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/baseline-const
        - ClimaAtmos.jl/.buildkite
        - config/base.yml
        - config/const.yml
      inputs:
        - config/base.yml
        - config/const.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/perf/benchmark_step.jl
      outputs:
        - results/nsys/baseline-const.nsys-rep
    nsys-baseline-const-to-sqlite:
      kind: shell-command
      environment: _system
      command: nsys export results/nsys/baseline-const.nsys-rep -t sqlite
        -o results/nsys/baseline-const.sqlite
      inputs:
        - results/nsys/baseline-const.nsys-rep
      outputs:
        - results/nsys/baseline-const.sqlite
    # nsys-mod-const:
    #   kind: sbatch
    #   environment: clima
    #   script_path: scripts/run-nsys.sh
    #   sbatch_options:
    #     - --gpus=1
    #     - --time=60
    #   args:
    #     - results/nsys/mod-const
    #     - ClimaAtmos.jl-mod/.buildkite
    #     - config/base.yml
    #     - config/const.yml
    #   inputs:
    #     - config/base.yml
    #     - config/const.yml
    #     - ClimaAtmos.jl-mod/src
    #     - ClimaAtmos.jl-mod/toml
    #     - ClimaAtmos.jl-mod/.buildkite/Manifest-v1.11.toml
    #     - ClimaAtmos.jl/perf/benchmark_step.jl
    #   outputs:
    #     - results/nsys/mod-const.nsys-rep
    # nsys-mod-const-to-sqlite:
    #   kind: shell-command
    #   environment: _system
    #   command: nsys export results/nsys/mod-const.nsys-rep -t sqlite -o
    #     results/nsys/mod-const.sqlite
    #   inputs:
    #     - results/nsys/mod-const.nsys-rep
    #   outputs:
    #     - results/nsys/mod-const.sqlite
    nsys-baseline-none:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/baseline-none
        - ClimaAtmos.jl/.buildkite
        - config/base.yml
      inputs:
        - config/base.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/perf/benchmark_step.jl
      outputs:
        - results/nsys/baseline-none.nsys-rep
    nsys-baseline-none-to-sqlite:
      kind: shell-command
      environment: _system
      command: nsys export results/nsys/baseline-none.nsys-rep -t sqlite
        -o results/nsys/baseline-none.sqlite
      inputs:
        - results/nsys/baseline-none.nsys-rep
      outputs:
        - results/nsys/baseline-none.sqlite
    baseline-none:
      kind: sbatch
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=60
      script_path: scripts/run.sh
      args:
        - ClimaAtmos.jl/.buildkite
        - scripts/run.jl
        - --job_id
        - baseline_none
        - --config_file
        - config/base.yml
      inputs:
        - scripts/run.jl
        - config/base.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
    baseline-const:
      kind: sbatch
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=60
      script_path: scripts/run.sh
      args:
        - ClimaAtmos.jl/.buildkite
        - scripts/run.jl
        - --job_id
        - baseline_const
        - --config_file
        - config/base.yml
        - --config_file
        - config/const.yml
      inputs:
        - scripts/run.jl
        - config/base.yml
        - config/const.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
    baseline-smag:
      kind: sbatch
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=60
      script_path: scripts/run.sh
      args:
        - ClimaAtmos.jl/.buildkite
        - scripts/run.jl
        - --job_id
        - baseline_smag
        - --config_file
        - config/base.yml
        - --config_file
        - config/smag.yml
      inputs:
        - scripts/run.jl
        - config/base.yml
        - config/smag.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
    # mod-const:
    #   kind: sbatch
    #   environment: clima
    #   sbatch_options:
    #     - --gpus=1
    #     - --time=60
    #   script_path: scripts/run.sh
    #   args:
    #     - ClimaAtmos.jl-mod/.buildkite
    #     - scripts/run.jl
    #     - --job_id
    #     - mod_const
    #     - --config_file
    #     - config/base.yml
    #     - --config_file
    #     - config/const.yml
    #   inputs:
    #     - scripts/run.jl
    #     - config/base.yml
    #     - config/const.yml
    #     - ClimaAtmos.jl-mod/src
    #     - ClimaAtmos.jl-mod/toml
    #     - ClimaAtmos.jl-mod/.buildkite/Manifest-v1.11.toml
    mod-smag:
      kind: sbatch
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=60
      script_path: scripts/run.sh
      args:
        - ClimaAtmos.jl-mod/.buildkite
        - scripts/run.jl
        - --job_id
        - mod_smag
        - --config_file
        - config/base.yml
        - --config_file
        - config/smag.yml
      inputs:
        - scripts/run.jl
        - config/base.yml
        - config/smag.yml
        - ClimaAtmos.jl-mod/src
        - ClimaAtmos.jl-mod/toml
        - ClimaAtmos.jl-mod/.buildkite/Manifest-v1.11.toml
    summarize:
      kind: python-script
      environment: py
      script_path: scripts/summarize.py
      inputs:
        - results/nsys
        - from_stage_outputs: baseline-none
        - from_stage_outputs: baseline-const
        - from_stage_outputs: mod-smag
        - from_stage_outputs: baseline-smag
      outputs:
        - path: results/summary.csv
          storage: git

notebooks:
  - path: notebooks/smag.ipynb
    environment: clima
    stage: smag-notebook # TODO: Create stage even if not in pipeline
    executed_ipynb_storage: git
