owner: petebachant
name: clima-horizontal-diffusion
title: CliMA horizontal diffusion
description: Optimizing performance of horizontal diffusion in ClimaAtmos.
git_repo_url: https://github.com/petebachant/clima-horizontal-diffusion

questions:
  - question: Why does horizontal diffusion (Smagorinsky and AMD)
      slow down ClimaAtmos so much, and is there anything we can do about it?
    hypothesis: There is probably some inefficiency in the CUDA kernels
      implementing horizontal diffusion that can be improved.
  - question: What is the computational cost of constant horizontal diffusion?
    answer: It's about 1--2%.
    evidence:
      - kind: result
        path: results/summary.csv
        description: Results from profiling runs with and without
          constant horizontal diffusion enabled.
  - question: Can we speed up constant horizontal diffusion?
    answer: By approximately 1%.
    evidence:
      - kind: git-diff
        repo_path: ClimaAtmos.jl-mod
        base_ref: 9f3e2b4
        compare_ref: main
        paths: []
        description: These are some changes made that produced a small speedup.
      - kind: result

environments:
  clima:
    kind: slurm
    host: clima.gps.caltech.edu
  py:
    path: requirements.txt
    kind: uv-venv
    prefix: .venv
    python: "3.13"

pipeline:
  stages:
    # gen-smag-state:
    #   kind: sbatch
    #   environment: clima
    #   script_path: scripts/run.sh
    #   sbatch_options:
    #     - --gpus=1
    #     - --time=30
    #   args:
    #     - ClimaAtmos.jl/.buildkite
    #     - scripts/gen_smag_state.jl
    #   inputs:
    #     - scripts/gen_smag_state.jl
    #     - config/base.yml
    #     - config/smag.yml
    #     - ClimaAtmos.jl/src
    #     - ClimaAtmos.jl/toml
    #     - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
    #   outputs:
    #     - path: results/smag_fixture.jld2
    #       storage: null
    # nsys-baseline:
    #   kind: sbatch
    #   environment: clima
    #   script_path: scripts/run-nsys.sh
    #   sbatch_options:
    #     - --gpus=1
    #     - --time=60
    #   args:
    #     - results/nsys/baseline
    #     - ClimaAtmos.jl/.buildkite
    #     - config/base.yml
    #     - config/smag.yml
    #   inputs:
    #     - config/base.yml
    #     - config/smag.yml
    #     - ClimaAtmos.jl/src
    #     - ClimaAtmos.jl/toml
    #     - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
    #     - ClimaAtmos.jl/perf/benchmark_step.jl
    #   outputs:
    #     - results/nsys/baseline.nsys-rep
    # nsys-baseline-to-sqlite:
    #   kind: shell-command
    #   environment: _system
    #   command: nsys export results/nsys/baseline.nsys-rep -t sqlite
    #     -o results/nsys/baseline.sqlite
    #   inputs:
    #     - results/nsys/baseline.nsys-rep
    #   outputs:
    #     - results/nsys/baseline.sqlite
    # nsys-mod:
    #   kind: sbatch
    #   environment: clima
    #   script_path: scripts/run-nsys.sh
    #   sbatch_options:
    #     - --gpus=1
    #     - --time=60
    #   args:
    #     - results/nsys/mod
    #     - ClimaAtmos.jl-mod/.buildkite
    #     - config/base.yml
    #     - config/smag.yml
    #   inputs:
    #     - config/base.yml
    #     - config/smag.yml
    #     - ClimaAtmos.jl-mod/src
    #     - ClimaAtmos.jl-mod/toml
    #     - ClimaAtmos.jl-mod/.buildkite/Manifest-v1.11.toml
    #     - ClimaAtmos.jl/perf/benchmark_step.jl
    #   outputs:
    #     - results/nsys/mod.nsys-rep
    # nsys-mod-to-sqlite:
    #   kind: shell-command
    #   environment: _system
    #   command: nsys export results/nsys/mod.nsys-rep -t sqlite
    #     -o results/nsys/mod.sqlite
    #   inputs:
    #     - results/nsys/mod.nsys-rep
    #   outputs:
    #     - results/nsys/mod.sqlite
    nsys-baseline-const:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/baseline-const
        - ClimaAtmos.jl/.buildkite
        - config/base.yml
        - config/const.yml
      inputs:
        - config/base.yml
        - config/const.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/perf/benchmark_step.jl
      outputs:
        - results/nsys/baseline-const.nsys-rep
    nsys-baseline-const-to-sqlite:
      kind: shell-command
      environment: _system
      command: nsys export results/nsys/baseline-const.nsys-rep -t sqlite
        -o results/nsys/baseline-const.sqlite
      inputs:
        - results/nsys/baseline-const.nsys-rep
      outputs:
        - results/nsys/baseline-const.sqlite
    nsys-mod-const:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/mod-const
        - ClimaAtmos.jl-mod/.buildkite
        - config/base.yml
        - config/const.yml
      inputs:
        - config/base.yml
        - config/const.yml
        - ClimaAtmos.jl-mod/src
        - ClimaAtmos.jl-mod/toml
        - ClimaAtmos.jl-mod/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/perf/benchmark_step.jl
      outputs:
        - results/nsys/mod-const.nsys-rep
    nsys-mod-const-to-sqlite:
      kind: shell-command
      environment: _system
      command: nsys export results/nsys/mod-const.nsys-rep -t sqlite -o
        results/nsys/mod-const.sqlite
      inputs:
        - results/nsys/mod-const.nsys-rep
      outputs:
        - results/nsys/mod-const.sqlite
    nsys-baseline-none:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - results/nsys/baseline-none
        - ClimaAtmos.jl/.buildkite
        - config/base.yml
      inputs:
        - config/base.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/perf/benchmark_step.jl
      outputs:
        - results/nsys/baseline-none.nsys-rep
    nsys-baseline-none-to-sqlite:
      kind: shell-command
      environment: _system
      command: nsys export results/nsys/baseline-none.nsys-rep -t sqlite
        -o results/nsys/baseline-none.sqlite
      inputs:
        - results/nsys/baseline-none.nsys-rep
      outputs:
        - results/nsys/baseline-none.sqlite
    baseline-none:
      kind: sbatch
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=60
      script_path: scripts/run.sh
      args:
        - ClimaAtmos.jl/.buildkite
        - scripts/run.jl
        - --job_id
        - baseline_none
        - --config_file
        - config/base.yml
      inputs:
        - scripts/run.jl
        - config/base.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
    baseline-const:
      kind: sbatch
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=60
      script_path: scripts/run.sh
      args:
        - ClimaAtmos.jl/.buildkite
        - scripts/run.jl
        - --job_id
        - baseline_const
        - --config_file
        - config/base.yml
        - --config_file
        - config/const.yml
      inputs:
        - scripts/run.jl
        - config/base.yml
        - config/const.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
    baseline-smag:
      kind: sbatch
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=60
      script_path: scripts/run.sh
      args:
        - ClimaAtmos.jl/.buildkite
        - scripts/run.jl
        - --job_id
        - baseline_smag
        - --config_file
        - config/base.yml
        - --config_file
        - config/smag.yml
      inputs:
        - scripts/run.jl
        - config/base.yml
        - config/smag.yml
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
    mod-const:
      kind: sbatch
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=60
      script_path: scripts/run.sh
      args:
        - ClimaAtmos.jl-mod/.buildkite
        - scripts/run.jl
        - --job_id
        - mod_const
        - --config_file
        - config/base.yml
        - --config_file
        - config/const.yml
      inputs:
        - scripts/run.jl
        - config/base.yml
        - config/const.yml
        - ClimaAtmos.jl-mod/src
        - ClimaAtmos.jl-mod/toml
        - ClimaAtmos.jl-mod/.buildkite/Manifest-v1.11.toml
    summarize:
      kind: python-script
      environment: py
      script_path: scripts/summarize.py
      inputs:
        - results/nsys
        - from_stage_outputs: baseline-none
        - from_stage_outputs: baseline-const
        - from_stage_outputs: mod-const
      outputs:
        - path: results/summary.csv
          storage: git
